# Build a release containing .zip of the (filtered) contents of the repository
# when a new tag is pushed with a semantic versioning format.
name: Build Releases

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check-out the repository under: $GITHUB_WORKSPACE/<repository-name>
      # Note: While this makes zipping the repository with a root folder easier,
      # all 'gh' commands must be executed after cd'ing into the sub-directory.
      - uses: actions/checkout@v3
        with:
          path: ${{ github.event.repository.name }}
          github_token: ${{ secrets.github_token }}


      # Create a zip of the repository.
      - name: Zip Repository (excludes .git*)
        run: |
          # Zip the contents underneath a root directory (the repository's name) as
          # required by Blender for <repository-name>/__init__.py style add-ons.
          # See below for single-file add-ons that do not need a root directory. 
          zip -r ${{ github.event.repository.name }}.zip \
            ${{ github.event.repository.name }} \
            -x "${{ github.event.repository.name }}/.git*"
          
          # If a root folder is not desired, use the following and comment out the above.
          #cd ${{ github.event.repository.name }}
          #zip -r ../${{ github.event.repository.name }}.zip . -x ".git*"
      
      # Create a new release using the tag name or commit id.

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
